---
- hosts: localhost
  name: Create instance and add to host group
  gather_facts: false
  vars:
    - vpc_id: vpc-aff1abcb
    - subnet_id: subnet-f12985a9
    - instance_type: t3.micro
    - aws_region: us-west-2 #oregon
    - image_id: ami-0ecc74eca1d66d8a6 #ubuntu
    - key_name: vec
    - public_ip: 34.209.65.108/32
  vars_files: #key info
    - playbooks/vars.yml
  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: sgvector
        description: allow ssh and 8080 ingress
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            ports:
              - 8080
              - 22
            cidr_ip: "{{ public_ip }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: security_group
    
